### PR TITLE
PLF-7975 Show/Hide Offline users Toggle tooltip in the Chat should be…

### PR DESCRIPTION
**Pull request by nttuyen**
- Update resource bundle

### CODE REVIEW

**Comment by trongtt** [comment]
This is about translation issue, so it should be done on Crowdin instead, no ?

**Comment by thomasdelhomenie** [comment]
@trongtt if it is only about translations update, yes you are right, it must be done in Crowdin.
But I think the goal of the issue is to display "Show offline users" when offline users are hidden, and "Hide offline users" when offline users are visible. @hghorbel am I right ?

**Comment by hghorbel** [comment]
@thomasdelhomenie Right, the goal is to have: 
- "Show offline users" when offline users are hidden
- "Hide offline users" when offline users are visible

**Comment by nttuyen** [comment]
@thomasdelhomenie , yes, after apply this PR, the tooltip will have that behavior, say "Show offline users" when offline users are hidden and "Hide offline users" when offline users are visible

- Because we already have javascript to change those tooltip, just the translation are wrong
exoplatform.chat.show.users --> Show/Hide offline users , that need to be changed to Show offline users
exoplatform.chat.hide.users --> Hide offline user --> good translation

**Comment by nttuyen** [comment]
Alright, we will update on CrownIn instead

**Pull request closed without merging**
