### PR TITLE
CHAT-774 Event with special characters "& is not displayed correctly …

### PR DESCRIPTION
**Pull request by trongtt**
…in the calendar application

### CODE REVIEW

**Comment by trongtt** [comment]
@thomasdelhomenie the xss issue in activity stream is actually a dedicated problem that need to encoding event data before displaying. We can easily reproduce the same problem when creating the xss event in Calendar app.

What I fixed in this PR is just not encoding event data before persisting into Calendar storage, same behavior in Calendar app.

**Comment by trongtt** [comment]
I just fixed the XSS issue in chat room which was already there before the fix.

**Comment by thomasdelhomenie** [comment]
ok. Is there an jira issue for the xss issue in calendar ? If no, please open it.

**Comment by trongtt** [comment]
I just created https://jira.exoplatform.org/browse/CAL-1302 for XSS issue in Calendar.

**Pull request merged**
