### PR TITLE
CHAT-193: Cannot save wiki if user's name or team's name contains spe…

### PR DESCRIPTION
**Pull request by nguyenthienhuong**
…cial characters

Fix description: Encode page's title before saving

### CODE REVIEW

**Comment by exo-swf** [comment]
Can one of the admins verify this patch?

**Comment by exo-swf** [comment]
Can one of the admins verify this patch?

**Comment by thomasdelhomenie** [comment]
OK to test.

**Comment by thomasdelhomenie** [comment]
OK to test

**Comment by exo-swf** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
