### PR TITLE
Fix/chat 510

### PR DESCRIPTION
**Pull request by gpicavet**

### CODE REVIEW

**Comment by gpicavet** [comment]
it seems standalone-server war has increased by 50% ... it should be possible to exclude some indirect dependencies

**Comment by thomasdelhomenie** [comment]
The PR looks good to me (and works fine).
@mgreau I just want you opinion on it please. We now use a class from org.exoplatform.commons:commons-component-common in the chat server. This artifact pulls a lot of transitive dependencies which makes the war getting really bigger, but we only need one class and one dependency (com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer) from that artifact. Is the fix ok for you ?

**Comment by mgreau** [comment]
Looks good.

@gpicavet can you update your commit to clean it up so that we can easily see the diff please.

Just execute the following command:
`mvn -Pformat-pom`
After that, you should have a better diff.
Then you can push force to erase your commit and update the PR.

Thanks

**Comment by gpicavet** [comment]
sorry i didn't check the result. Here is a better formatted version. Regards

**Comment by mgreau** [comment]
Thanks ;)
LGTM

**Comment by thomasdelhomenie** [comment]
@gpicavet it seems you used 2 accounts for your commits. Can you update the PR to use only the right account (gpicavet) please ?

**Pull request closed without merging**
