### PR TITLE
CHAT-570 getStatus is called very frequently

### PR DESCRIPTION
**Pull request by boubaker**

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
This PR avoids to execute multiple getStatus requests in parallel, which is a good thing :+1: , but I don't think it fixes the root cause. The getStatus call must be done every 15s (by default), and according to the tests it is done a lot more than that. I think we should understand and fix this root issue.

**Comment by boubaker** [comment]
The getStatus request is called every 2.5 seconds to refresh the selected room status, as you can see here:
https://github.com/exo-addons/chat-application/blob/develop/application/src/main/webapp/js/chat.js#L3106
This parameter is embedded and isn't configurable. IMO, all we can do is to make this configurable. WDYT?

**Comment by thomasdelhomenie** [comment]
Yes, it seems to be due to this line. I don't think it is still needed so we should probably remove it (to be tested).

**Comment by boubaker** [comment]
ok, done. Thx @thomasdelhomenie

**Comment by trongtt** [comment]
Maybe you also want to remove the variable `roomUserInterval` from this line https://github.com/exo-addons/chat-application/pull/87/files#diff-156a457ac3b8346db0b3431d19a01c3bL3063

**Comment by boubaker** [comment]
> Maybe you also want to remove the variable roomUserInterval

Done, good catch! This variable is not used anymore. Thank you.

**Comment by boubaker** [comment]
Merged to develop

**Pull request closed without merging**
